# Generated by Django 4.0 on 2021-12-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_slill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slill',
            new_name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
